UMAR proxy is set!input dir\\192.168.38.7\public$\Users\AKuštrin\Dinamièni_faktorski_model\
Directory exists: TRUE
Can access: TRUE
files\\192.168.38.7\public$\Users\AKuštrin\Dinamièni_faktorski_model\smtk_2025_q1.xlsx
Processing file:smtk_2025_q1.xlsx

Output written to:\\192.168.38.7\public$\Avtomatizacija\umar-data\JK\umar_serije_podatki_JK.xlsx

Q sheet rows:117

M sheet rows:351

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> withVisible -> eval -> eval -> source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '\\192.168.38.7\public$\Avtomatizacija\umar-automation-scripts\R\umar_add_new_data_full.R': No such file or directory
Execution halted
